package main

// Raw LibCrypt copy (PSX).
//
// A normal burn lets the drive generate the whole subchannel, so the
// modified Q of the LibCrypt sectors is lost and the copy needs sbi.zip. In
// raw mode (cdrdao generic-mmc-raw, 96 byte raw P-W, "RAW-DAO 96") the host
// sends the subchannel with every sector. Disc Tools' cdrdao has an option
// (patches/cdrdao-raw-q-from-image.patch, driver option 0x400) that writes
// the Q given in the image instead of the generated one; the image carries a
// Q only for the protected LibCrypt sectors, every other sector keeps the Q
// generated by cdrdao. The result is a CD-R with the same LibCrypt sectors
// as the original disc, and without its other subchannel read errors.
//
// It needs a drive that accepts raw 96 byte P-W writing and writes the Q as
// sent; cdrdao stops with an error when the drive refuses the mode.

import (
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// driver option of the patched cdrdao: Q of the image for the sectors that
// carry one
const cdrdaoRawQDriver = "generic-mmc-raw:0x400"

// copyRangeWithSubQ copies length bytes of 2352-byte sectors from src and
// writes each one followed by 96 bytes of raw interleaved P-W: the Q of
// subQ[frame] where given, zero otherwise. firstLBA is the LBA of the first
// sector of the range.
func copyRangeWithSubQ(src, dst string, offset, length int64, firstLBA int, subQ map[int][12]byte, cancel <-chan struct{}, onBytes func(int64)) error {
	if offset < 0 || length < 0 || length%rawSectorLen != 0 {
		return errors.New("invalid raw LibCrypt track range")
	}
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if _, err := in.Seek(offset, io.SeekStart); err != nil {
		return err
	}
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	const chunk = 256
	ibuf := make([]byte, chunk*rawSectorLen)
	obuf := make([]byte, chunk*rawSubStride)
	lba := firstLBA
	for remaining := length / rawSectorLen; remaining > 0; {
		select {
		case <-cancel:
			_ = out.Close()
			return errors.New("cancelled")
		default:
		}
		n := int64(chunk)
		if remaining < n {
			n = remaining
		}
		if _, err := io.ReadFull(in, ibuf[:n*rawSectorLen]); err != nil {
			_ = out.Close()
			return err
		}
		for k := 0; k < int(n); k++ {
			o := obuf[k*rawSubStride : (k+1)*rawSubStride]
			copy(o, ibuf[k*rawSectorLen:(k+1)*rawSectorLen])
			sub := o[rawSectorLen:]
			for i := range sub {
				sub[i] = 0
			}
			if q, ok := subQ[lba+k+150]; ok {
				qIntoRaw(sub, q)
			}
		}
		if _, err := out.Write(obuf[:n*rawSubStride]); err != nil {
			_ = out.Close()
			return err
		}
		lba += int(n)
		remaining -= n
		if onBytes != nil {
			onBytes(n * rawSectorLen)
		}
	}
	return out.Close()
}

// chooseLibCryptBurn asks how to burn a LibCrypt image. ok is false when
// the user goes back. Without LibCrypt, or without the full Q of the
// protected sectors (.sbi only), there is nothing to ask.
func (a *App) chooseLibCryptBurn(info imageLibCryptInfo) (raw bool, ok bool) {
	if info.Q == nil {
		return false, true
	}
	i, ok := a.menu("PSX LIBCRYPT DISC", []string{
		"STANDARD BURN (+ SBI.ZIP)",
		"RAW BURN WITH LIBCRYPT SUBCHANNEL",
	}, 0)
	if !ok {
		return false, false
	}
	return i == 1, true
}

// burnCueRawLibCrypt burns a CUE/BIN with the LibCrypt Q written on the disc.
func (a *App) burnCueRawLibCrypt(cue, speed string, needsAudioSwap bool, ex burnExtras) {
	toc, cleanup, err := a.stageCueTOC(cue, ex.rawQ)
	if err != nil {
		a.message("BURN FAILED", []string{"Could not prepare the raw LibCrypt copy:", err.Error(), "Nothing was written to the disc."})
		return
	}
	defer cleanup()

	args := []string{"write", "--device", device, "--driver", cdrdaoRawQDriver, "--eject", "-n"}
	if speed != "" {
		args = append(args, "--speed", speed)
	}
	if needsAudioSwap {
		args = append(args, "--swap")
	}
	args = append(args, toc)
	cmd := exec.Command(helper("cdrdao"), args...)
	cmd.Dir = filepath.Dir(toc)
	appendDiscToolsLog(fmt.Sprintf("raw LibCrypt burn of %s: %d protected sector(s), cdrdao %s", filepath.Base(cue), len(ex.rawQ), strings.Join(args, " ")))
	if err := a.runJob("BURNING DISC", cmd); err != nil {
		a.message("BURN FAILED", []string{err.Error(), "", "The drive may not support raw 96 byte subchannel writing.", "Use STANDARD BURN: the copy then needs sbi.zip."})
		return
	}
	a.message("BURN COMPLETE", append([]string{"The disc was written with the LibCrypt subchannel."}, ex.note...))
}
